/** @bm/catalog — interfaces and primitives land with their owning P1 stories. */
export const PACKAGE = "@bm/catalog" as const;

export {
  SERVICE_UNITS,
  ATTRIBUTION_ROLES,
  isAttributionRole,
  createService,
  updateService,
  getService,
  listServices,
  setServicePrice,
  listServicePrices,
  resolveServicePriceAt,
  getServiceAttributionRole,
  checkBookingAttribution,
  serviceAttributionRole,
  TAX_TREATMENTS,
  DEFAULT_TAX_TREATMENT,
  KENYA_VAT_RATE_BPS,
  isTaxTreatment,
  getServiceTaxTreatment,
  serviceTaxTreatment,
  computeLineTax,
  ServicePriceOrderError,
  type ServiceUnit,
  type LineTax,
  type AttributionCheck,
  type CreateServiceInput,
  type UpdateServiceInput,
  type Executor,
} from "./services.js";

export {
  createStaff,
  updateStaff,
  setStaffActive,
  getStaff,
  listStaff,
  type CreateStaffInput,
  type UpdateStaffInput,
} from "./staff.js";

export {
  SUBSCRIPTION_PERIODS,
  isSubscriptionPeriod,
  addPeriod,
  PlanPriceOrderError,
  createPlan,
  updatePlan,
  getPlan,
  listPlans,
  setPlanPrice,
  listPlanPrices,
  resolvePlanPriceAt,
  type CreatePlanInput,
  type UpdatePlanInput,
} from "./subscriptions.js";

export {
  SLOT_GENERATION_HORIZON_DAYS,
  hmToMinutes,
  minutesToHm,
  slotWindows,
  addDaysIso,
  dayOfWeekIso,
  enumerateSlotDates,
  createSchedule,
  updateSchedule,
  getSchedule,
  listSchedules,
  generateSlotsForSchedule,
  regenerateActiveSlots,
  deleteFutureUnbookedSlots,
  resyncScheduleSlots,
  listSlotsWithRemaining,
  getSlotWithRemaining,
  isSlotPast,
  browseServiceSlots,
  bookSlot,
  SlotNotFoundError,
  SlotFullError,
  ServicePriceMissingError,
  DuplicateBookingError,
  BookingNotFoundError,
  ServiceMismatchError,
  BookingAlreadyCancelledError,
  slotStartUtcMs,
  isWithinRescheduleCutoff,
  rescheduleBooking,
  cancelBooking,
  type RescheduleResult,
  type CancelResult,
  type SlotWindow,
  type CreateScheduleInput,
  type UpdateScheduleInput,
  type SlotWithRemaining,
  type BrowseSlot,
  type BookSlotInput,
  type BookSlotResult,
} from "./schedules.js";
